### ISSUE TITLE
Error update-dev Missing requirement: CFEclipse

### ISSUE THREAD

**Issue by bardware** [cfeclipse/cfeclipse#70]
I see you pushed a new version to update site cfeclipse-dev
I tried to install to eclipse neon and got the following error message
```
Cannot complete the install because one or more required items could not be found.
  Software being installed: CFEclipse (including MXUnit and Frameworks) 1.5.1.201607220626 (org.cfeclipse.cfml.feature.feature.group 1.5.1.201607220626)
  Missing requirement: CFEclipse (including MXUnit and Frameworks) 1.5.1.201607220626 (org.cfeclipse.cfml.feature.feature.group 1.5.1.201607220626) requires 'org.mxunit.eclipseplugin.feature.feature.group 0.0.0' but it could not be found
```

You had a version there before - CFLint didn't seem to work there.
This version is 1.5.1 again, not 1.5.2

**Comment by dajester2013** [comment]
Can you make sure you have both the update and update-dev sites added to eclipse? You need both if you are wanting to install the dev version.

**Comment by bardware** [comment]
I now added the original update site, installed 1.5.1 from there and tried to install latest from the update-dev site. I got a dialog informing of some version conflict. Seems like I ended up with 1.5.0.
I started with a small Eclipse Runtime Platform Binary in the first place.

**Comment by dajester2013** [comment]
I suppose I should have been more clear.  When I intend to install the dev version in a clean version of eclipse, I:

* add the main update site, without installing anything
* add the dev update site
* install the latest cfeclipse from the dev update site

You should be able to just uninstall the cfeclipse and mxunit plugins, and then re-install from the dev update site.

**Comment by bardware** [comment]
It works that way, thank you!

**Comment by denuno** [comment]
I think this issue was really related to the biggest change for 1.5.2 thus far, which is that both the cfparser and cflint libs have been split into their own eclipse plugins-- and the fact that I'd fubar'ed the dev update site when doing so.  :-P

I got it corrected over the weekend.

So cflint and cfparser both have update sites now, which are automatically added when you install CFE, and thus we can update them independently (many of the best fixes lately have been in the parser or the linter, so it made sense to split them out-- plus if we do do a rewrite for 2.0, this'll be handy for that too).  Thanks for testing this (ha!), and there will still be a bit more to test, as we'll have to be sure updates to cfparser and cflint get pulled in automatically when you check for updates, but since you were able to install CFE successfully today, that's a good sign.  :-)
